# Generated by Django 4.0.2 on 2022-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('serial_number', models.IntegerField()),
                ('unique_id', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('re_enter_password', models.CharField(max_length=10)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
            ],
        ),
    ]
